apiVersion: v1
kind: ConfigMap
metadata:
  name: huntsphere-config
  namespace: huntsphere
data:
  DATABASE_URL: postgresql://huntsphere_user:huntsphere_pass@postgres:5432/huntsphere_db
  REDIS_URL: redis://redis:6379/0
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "http://localhost:3000,https://huntsphere.example.com"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_HOURS: "24"
  FEED_CHECK_INTERVAL_MINUTES: "30"
---
apiVersion: v1
kind: Secret
metadata:
  name: huntsphere-secrets
  namespace: huntsphere
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  OPENAI_API_KEY: ""
  XSIAM_API_KEY: ""
  DEFENDER_CLIENT_SECRET: ""
  WIZ_CLIENT_SECRET: ""
  SMTP_PASSWORD: ""
  SLACK_BOT_TOKEN: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: huntsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: huntsphere_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: huntsphere-secrets
              key: SECRET_KEY
        - name: POSTGRES_DB
          value: huntsphere_db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: huntsphere
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: huntsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: huntsphere
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: huntsphere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: huntsphere-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: huntsphere-config
        - secretRef:
            name: huntsphere-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: huntsphere
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: huntsphere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: huntsphere-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://backend:8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: huntsphere
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
